import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { Users, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHeading } from '@/components/university/page-heading';
import { clubs, pageMeta } from '@/lib/university';
import lifeAsset from '@/assets/student-community.jpeg.asset.json';
const life = lifeAsset.url;
import formalAsset from '@/assets/uniform-formal.png.asset.json';
import poloAsset from '@/assets/uniform-polo.png.asset.json';
import jacketAsset from '@/assets/uniform-jacket.png.asset.json';
import engineeringAsset from '@/assets/uniform-engineering.png.asset.json';
import tieAsset from '@/assets/uniform-tie-logo.png.asset.json';
const uniformImages = [formalAsset, poloAsset, jacketAsset, engineeringAsset, tieAsset];
export const Route = createFileRoute('/student-life')({ head: () => pageMeta('ชีวิตนักศึกษา', 'เครื่องแบบนักศึกษา ชั้นปี 1–6 ชมรมศิลปวัฒนธรรม ดนตรี กีฬา และสโมสรนักศึกษาศิลปาวรณ์'), component: StudentLife });
const uniforms=[{name:'ชุดนักศึกษาทางการ',text:'เครื่องแบบสำหรับการเรียนและกิจกรรมทางการของมหาวิทยาลัย รายละเอียดการแต่งกายให้ยึดตามข้อกำหนดของคณะและกิจกรรม'},{name:'เสื้อโปโล',text:'เสื้อโปโลสำหรับกิจกรรมของคณะและมหาวิทยาลัย ตามรูปแบบที่หน่วยงานกำหนด'},{name:'Jacket',text:'เสื้อแจ็กเก็ตประจำคณะและกิจกรรม สะท้อนอัตลักษณ์ของชาวศิลปาวรณ์'},{name:'ช็อปวิศวะ',text:'ชุดปฏิบัติงานสำหรับการเรียนในห้องปฏิบัติการและพื้นที่ฝึกงาน โดยคำนึงถึงความปลอดภัย'},{name:'เนคไท & โลโก้',text:'เครื่องหมายประจำมหาวิทยาลัยและเนคไทสำหรับเครื่องแบบนักศึกษาทางการ'}];
const yearTexts=['เริ่มต้นชีวิตมหาวิทยาลัย ทำความรู้จักเพื่อน คณะ และชุมชนศิลปาวรณ์','สำรวจความสนใจ ต่อยอดทักษะ และมีส่วนร่วมกับกิจกรรมที่คุณรัก','ลงลึกในศาสตร์ของตนเอง เชื่อมโยงความรู้กับประสบการณ์จริง','พัฒนาผลงาน เตรียมพร้อมสำหรับเส้นทางหลังมหาวิทยาลัย','ต่อยอดการเรียนรู้และการปฏิบัติงานตามแผนการศึกษาของหลักสูตร','ก้าวสู่ความเชี่ยวชาญและเตรียมความพร้อมตามข้อกำหนดของหลักสูตร'];
function StudentLife(){const [uniform,setUniform]=useState(0);const [year,setYear]=useState(1);return <><PageHeading english="LIFE AT SINLAPAWORN" title="ชีวิตในรั้วศิลปาวรณ์" description="มิตรภาพ ความทรงจำ และพื้นที่ให้คุณเติบโตในแบบของตัวเอง"/><section className="section"><div className="site-container two-column"><img className="about-photo" src={life} width={768} height={1024} alt="ภาพสุนัขในชุมชนศิลปาวรณ์"/><div><p className="eyebrow">OUR UNIFORM</p><h2 className="section-title">เครื่องแบบที่เชื่อมโยงเรา</h2><div className="student-tabs">{uniforms.map((u,i)=><Button key={u.name} size="sm" variant={uniform===i?'default':'outline'} onClick={()=>setUniform(i)} aria-pressed={uniform===i}>{u.name}</Button>)}</div><img className="uniform-image" src={uniformImages[uniform]?.url} width={1107} height={768} alt={uniforms[uniform]?.name}/><div className="detail-panel" aria-live="polite"><h3>{uniforms[uniform]?.name}</h3><p>{uniforms[uniform]?.text}</p></div></div></div></section><section className="section explore-section"><div className="site-container"><p className="eyebrow">EVERY YEAR, A NEW CHAPTER</p><h2 className="section-title">ทุกชั้นปี มีเรื่องราวของตัวเอง</h2><div className="year-grid">{[1,2,3,4,5,6].map(y=><Button key={y} variant={year===y?'default':'outline'} onClick={()=>setYear(y)} aria-pressed={year===y}>ชั้นปีที่ {y}</Button>)}</div><div className="detail-panel" aria-live="polite"><h3>ชั้นปีที่ {year}</h3><p>{yearTexts[year-1]}</p></div></div></section><section className="section"><div className="site-container"><p className="eyebrow">FIND YOUR COMMUNITY</p><h2 className="section-title">ชมรมและกิจกรรมนักศึกษา</h2><p className="section-description">ค้นพบเพื่อนที่มีความสนใจเดียวกัน ผ่านศิลปวัฒนธรรม ดนตรี กีฬา และการสร้างสรรค์</p><div className="club-list">{clubs.map(c=><div key={c}><Users/><span>{c}</span></div>)}</div></div></section><section className="contact-band"><div className="site-container"><div><h2>สโมสรนักศึกษา</h2><p>เชื่อมต่อกิจกรรมและชุมชนนักศึกษา ผ่านช่องทางติดต่อของศิลปาวรณ์</p></div><Button asChild variant="outline"><Link to="/contact">ติดต่อสโมสรนักศึกษา<ArrowUpRight/></Link></Button></div></section></>;}
